# Generated by Django 5.0 on 2024-02-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0002_rename_files_myfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehash',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='myfileupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
